//
// Created by Темыч on 07.12.2020.
//

#ifndef BONKSCRIPT_COMMAND_LINE_ARGUMENTS_H
#define BONKSCRIPT_COMMAND_LINE_ARGUMENTS_H

#include "../utils/args.hpp"

enum argv_names {
    E_ARGV_NAME_HELP,
    E_ARGV_NAME_OUTPUT_FILE,
    E_ARGV_NAME_AST,
    E_ARGV_NAME_TARGET,
    E_ARGV_NAME_LOG_FILE
};

#endif //BONKSCRIPT_COMMAND_LINE_ARGUMENTS_H
