
#include "commands.h"

const uint64_t compiler_vendor = 0x00010000; // v1.0
const uint32_t compiler_magic = 'rede';

const unsigned long long PROC_FLAG_MASK_FLOATS =
    (1 << PROC_FLAG_FLOAT64) |
    (1 << PROC_FLAG_FLOAT32);

const unsigned long long PROC_FLAG_MASK_SIGNED_INTS =
    (1 << PROC_FLAG_INT64) |
    (1 << PROC_FLAG_INT32) |
    (1 << PROC_FLAG_INT16) |
    (1 << PROC_FLAG_INT8);

const unsigned long long PROC_FLAG_MASK_UNSIGNED_INTS =
    (1 << PROC_FLAG_UNSIGNED_INT64) |
    (1 << PROC_FLAG_UNSIGNED_INT32) |
    (1 << PROC_FLAG_UNSIGNED_INT16) |
    (1 << PROC_FLAG_UNSIGNED_INT8);

const unsigned long long PROC_FLAG_MASK_INTS =
    PROC_FLAG_MASK_SIGNED_INTS |
    PROC_FLAG_MASK_UNSIGNED_INTS;

const unsigned long long PROC_FLAG_MASK_DECIMALS =
    PROC_FLAG_MASK_INTS |
    PROC_FLAG_MASK_FLOATS;

const unsigned long long PROC_COMMAND_FLAGS[] = {
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_PUSH
    0,                       // PROC_COMMAND_POP
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_ADD
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_SUBTRACT
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_MULTIPLY
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_DIVIDE
    PROC_FLAG_MASK_FLOATS,   // PROC_COMMAND_SQRT
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_IN
    PROC_FLAG_MASK_DECIMALS, // PROC_COMMAND_OUT
    0,                       // PROC_COMMAND_HLT
    0,                       // PROC_COMMAND_NOP
};

const size_t PROC_FLAG_SIZES[] = {
    0, // PROC_FLAG_NONE
    8, // PROC_FLAG_FLOAT64
    4, // PROC_FLAG_FLOAT32
    8, // PROC_FLAG_INT64
    4, // PROC_FLAG_INT32
    2, // PROC_FLAG_INT16
    1, // PROC_FLAG_INT8
    8, // PROC_FLAG_UNSIGNED_INT64
    4, // PROC_FLAG_UNSIGNED_INT32
    2, // PROC_FLAG_UNSIGNED_INT16
    1  // PROC_FLAG_UNSIGNED_INT8
};
