

#include "registers.h"

const size_t PROC_REGISTER_OFFSETS[] = {
    0,  // PROC_REGISTER_RIP
    8,  // PROC_REGISTER_RSP
    16, // PROC_REGISTER_RAX
    24, // PROC_REGISTER_RBX
    32, // PROC_REGISTER_RCX
    40, // PROC_REGISTER_RDX
    16, // PROC_REGISTER_EAX
    24, // PROC_REGISTER_EBX
    32, // PROC_REGISTER_ECX
    40, // PROC_REGISTER_EDX
    16, // PROC_REGISTER_AX
    24, // PROC_REGISTER_BX
    32, // PROC_REGISTER_CX
    40, // PROC_REGISTER_DX
    17, // PROC_REGISTER_AH
    16, // PROC_REGISTER_AL
    25, // PROC_REGISTER_BH
    24, // PROC_REGISTER_BL
    33, // PROC_REGISTER_CH
    32, // PROC_REGISTER_CL
    41, // PROC_REGISTER_DH
    40  // PROC_REGISTER_DL
};

const size_t PROC_REGISTER_SIZES[] = {
    8, // PROC_REGISTER_RIP
    8, // PROC_REGISTER_RSP
    8, // PROC_REGISTER_RAX
    8, // PROC_REGISTER_RBX
    8, // PROC_REGISTER_RCX
    8, // PROC_REGISTER_RDX
    4, // PROC_REGISTER_EAX
    4, // PROC_REGISTER_EBX
    4, // PROC_REGISTER_ECX
    4, // PROC_REGISTER_EDX
    2, // PROC_REGISTER_AX
    2, // PROC_REGISTER_BX
    2, // PROC_REGISTER_CX
    2, // PROC_REGISTER_DX
    1, // PROC_REGISTER_AH
    1, // PROC_REGISTER_AL
    1, // PROC_REGISTER_BH
    1, // PROC_REGISTER_BL
    1, // PROC_REGISTER_CH
    1, // PROC_REGISTER_CL
    1, // PROC_REGISTER_DH
    1  // PROC_REGISTER_DL
};
